/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//askdhbfaksv
public class Library {
	/* Add this function */
	public static void main (String arg[]) {
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("When there's a fire, commit and push.");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
//sdfhdashg