/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	/* Add this function */
	public static void main (String arg[]) {
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("When there's a fire, commit and push.");
		System.out.println("kuh.");

			System.out.println("When there is a fire, commit and push.");
// >>>>>>> branch 'PP' of https://github.com/yylukad/comp3111-lab1-demo.git
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
